package media

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	seekThumbnailCommand  = "ffmpeg"
	seekThumbnailInterval = 5 * time.Second
	seekThumbnailTimeout  = 30 * time.Minute
)

// SeekThumbnailCache stores preview frames generated by the background worker.
// Playback requests only read these files and never start ffmpeg.
type SeekThumbnailCache struct {
	root string
}

func NewSeekThumbnailCache(thumbnailsDir string) *SeekThumbnailCache {
	return &SeekThumbnailCache{root: filepath.Join(thumbnailsDir, "seek")}
}

func (c *SeekThumbnailCache) Read(_ context.Context, contentKey string, positionMs int64) ([]byte, error) {
	return os.ReadFile(SeekThumbnailPath(c.root, contentKey, positionMs))
}

// GenerateSeekThumbnails decodes a video once in the background and persists
// one preview frame per interval. A temporary directory keeps partial output
// invisible when generation is canceled or fails.
func GenerateSeekThumbnails(
	ctx context.Context, videoPath, thumbnailsDir, contentKey string,
) error {
	root := filepath.Join(thumbnailsDir, "seek")
	target := SeekThumbnailDir(root, contentKey)
	if info, err := os.Stat(target); err == nil && info.IsDir() {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(target), thumbnailDirPerm); err != nil {
		return fmt.Errorf("シークサムネイルの置き場所を作れません: %w", err)
	}

	temporary, err := os.MkdirTemp(filepath.Dir(target), ".seek-*")
	if err != nil {
		return fmt.Errorf("シークサムネイルの一時領域を作れません: %w", err)
	}
	defer func() { _ = os.RemoveAll(temporary) }()

	processCtx, cancel := context.WithTimeout(ctx, seekThumbnailTimeout)
	defer cancel()
	output := filepath.Join(temporary, "%06d.jpg")
	args := seekThumbnailArgs(videoPath, output)
	if combined, runErr := exec.CommandContext(processCtx, seekThumbnailCommand, args...).CombinedOutput(); runErr != nil {
		if processCtx.Err() != nil {
			return fmt.Errorf("シークサムネイル生成を中断しました: %w", processCtx.Err())
		}
		return fmt.Errorf("%s が失敗しました (%s): %w: %s",
			seekThumbnailCommand, videoPath, runErr, firstLine(combined))
	}
	if _, err := os.Stat(filepath.Join(temporary, "000000.jpg")); err != nil {
		return fmt.Errorf("シークサムネイルが生成されませんでした (%s): %w", videoPath, err)
	}
	if err := os.Rename(temporary, target); err != nil {
		if info, statErr := os.Stat(target); statErr == nil && info.IsDir() {
			return nil
		}
		return fmt.Errorf("シークサムネイルを確定できません: %w", err)
	}
	return nil
}

func SeekThumbnailDir(root, contentKey string) string {
	safe := thumbnailFileName(contentKey)
	prefix := safe
	if len(prefix) > 2 {
		prefix = prefix[:2]
	}
	return filepath.Join(root, prefix, safe)
}

func SeekThumbnailPath(root, contentKey string, positionMs int64) string {
	index := max(int64(0), positionMs/seekThumbnailInterval.Milliseconds())
	return filepath.Join(SeekThumbnailDir(root, contentKey), fmt.Sprintf("%06d.jpg", index))
}

// RemoveSeekThumbnails removes the completed cache for one content key.
func RemoveSeekThumbnails(thumbnailsDir, contentKey string) error {
	root := filepath.Join(thumbnailsDir, "seek")
	if err := os.RemoveAll(SeekThumbnailDir(root, contentKey)); err != nil {
		return fmt.Errorf("シークサムネイルを削除できません: %w", err)
	}
	return nil
}

// RemoveOrphanSeekThumbnails removes completed caches that no longer have a
// video row. Temporary directories are ignored because a worker may still be
// generating them while a scan is being finalized.
func RemoveOrphanSeekThumbnails(
	thumbnailsDir string, contentKeys map[string]struct{},
) (int, error) {
	root := filepath.Join(thumbnailsDir, "seek")
	prefixes, err := os.ReadDir(root)
	if os.IsNotExist(err) {
		return 0, nil
	}
	if err != nil {
		return 0, fmt.Errorf("シークサムネイルの置き場所を読めません: %w", err)
	}

	keep := make(map[string]struct{}, len(contentKeys))
	for contentKey := range contentKeys {
		keep[thumbnailFileName(contentKey)] = struct{}{}
	}

	removed := 0
	for _, prefix := range prefixes {
		if !prefix.IsDir() {
			continue
		}
		prefixPath := filepath.Join(root, prefix.Name())
		entries, err := os.ReadDir(prefixPath)
		if err != nil {
			return removed, fmt.Errorf("シークサムネイルを読めません (%s): %w", prefixPath, err)
		}
		for _, entry := range entries {
			if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".seek-") {
				continue
			}
			if _, ok := keep[entry.Name()]; ok {
				continue
			}
			if err := os.RemoveAll(filepath.Join(prefixPath, entry.Name())); err != nil {
				return removed, fmt.Errorf("孤児シークサムネイルを削除できません (%s): %w", entry.Name(), err)
			}
			removed++
		}
	}
	return removed, nil
}

func seekThumbnailArgs(videoPath, outputPattern string) []string {
	return []string{
		"-nostdin",
		"-v", "error",
		"-i", videoPath,
		"-vf", "select='isnan(prev_selected_t)+gte(t-prev_selected_t\\,5)',scale=min(320\\,iw):-2,format=yuvj420p",
		"-fps_mode", "vfr",
		"-q:v", "4",
		"-start_number", "0",
		"-y",
		outputPattern,
	}
}
