package httpapi

import (
	"context"
	"errors"
	"io/fs"
	"log/slog"
	"net/http"
	"strconv"

	"github.com/syudead/vv/internal/domain"
	"github.com/syudead/vv/internal/httpapi/gen"
)

// GetVideoSeekThumbnail returns a JPEG generated by the background thumbnail job.
func (s *server) GetVideoSeekThumbnail(
	w http.ResponseWriter,
	r *http.Request,
	id gen.VideoId,
	params gen.GetVideoSeekThumbnailParams,
) {
	video, ok := s.lookupVideo(w, r, id)
	if !ok {
		return
	}
	if video.ProbeState != domain.ProbeStateDone || video.DurationMs == nil || *video.DurationMs <= 0 || video.VideoCodec == "" {
		s.writeError(w, http.StatusConflict, codeConflict, "この動画はプレビューに必要な解析情報がありません")
		return
	}
	if params.PositionMs < 0 || params.PositionMs >= *video.DurationMs {
		s.invalidRequest(w, "positionMsは動画の範囲内で指定してください")
		return
	}
	if s.artifacts == nil {
		s.internalError(w, "シークプレビューの保存先が設定されていません", nil)
		return
	}

	image, err := s.artifacts.SeekThumbnail(video.ContentKey, params.PositionMs)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		s.logger.Info("シークプレビューは生成中です",
			slog.Int64("video", video.ID), slog.Any("error", err))
		s.writeError(w, http.StatusConflict, codeConflict, "シークプレビューは生成中です")
		return
	case err != nil && errors.Is(r.Context().Err(), context.Canceled):
		return
	case err != nil:
		s.internalError(w, "シークプレビューを読み出せませんでした", err)
		return
	}
	if len(image) == 0 {
		s.internalError(w, "シークプレビューを読み出せませんでした", errors.New("生成画像が空です"))
		return
	}

	// 版の有無によらず、使うたびに確かめさせる（contracts/guest-api.md §5）。
	// If-None-Match が一致すれば 304 を返し、画像は送らない。
	etag := bytesETag(image)
	setRevalidate(w, etag)
	if etagMatches(r.Header.Get("If-None-Match"), etag) {
		w.WriteHeader(http.StatusNotModified)
		return
	}
	w.Header().Set("Content-Type", "image/jpeg")
	w.Header().Set("Content-Length", strconv.Itoa(len(image)))
	w.WriteHeader(http.StatusOK)
	if _, err := w.Write(image); err != nil {
		s.logger.Debug("シークプレビューを書き出せませんでした", slog.Int64("video", video.ID), slog.Any("error", err))
	}
}
