// Documentation site. It publishes docs/, specs/ and ARCHITECTURE.md in their
// repository layout, and their Japanese translations under /ja/. Documents are
// read in place: the repository root is srcDir, and everything else is
// excluded with srcExclude.
import fs from 'node:fs'
import path from 'node:path'
import { slug } from 'github-slugger'
import { defineConfig, type DefaultTheme } from 'vitepress'
import type MarkdownIt from 'markdown-it'

const repoRoot = path.resolve(import.meta.dirname, '../..')
const github = 'https://github.com/syudead/vv'
const branch = 'main'

// Published documents. Other Markdown (agent instructions in .agents/ and
// .claude/, the root README) is not published. ja/ is generated by
// translate/site.mjs before every build and is not version controlled.
const published = ['docs', 'specs', 'ARCHITECTURE.md', 'ja']
const hasJa = fs.existsSync(path.join(repoRoot, 'ja'))

// リポジトリ直下のうち、公開するものとこのサイト自身以外を全て外す。新しい
// ディレクトリが増えても、公開する側へ入れない限り出ない。
const srcExclude = [
  '**/node_modules/**',
  'docs-site/.vitepress/**',
  ...fs
    .readdirSync(repoRoot, { withFileTypes: true })
    .filter((e) => !published.includes(e.name) && e.name !== 'docs-site')
    .map((e) => (e.isDirectory() ? `${e.name}/**` : e.name)),
]

// README.md はディレクトリの入口なので index として出す。/docs/how-to/ の
// ようなディレクトリの URL で開ける。
function rewrite(id: string): string {
  if (id === 'docs-site/index.md') return 'index.md'
  return id.replace(/(^|\/)README\.md$/, '$1index.md')
}

const imageExt = /\.(png|jpe?g|gif|svg|webp)$/i

function isPublished(p: string): boolean {
  return published.some((dir) => p === dir || p.startsWith(dir + '/'))
}

function stat(p: string): fs.Stats | undefined {
  try {
    return fs.statSync(path.join(repoRoot, p))
  } catch {
    return undefined
  }
}

function hasIndex(dir: string): boolean {
  return ['README.md', 'index.md'].some((name) => stat(path.posix.join(dir, name))?.isFile())
}

// resolveLink rewrites a link in document `from` (a path from the repository
// root) so it works on the site. Published documents and images stay as they
// are (README.md becomes index.md); other repository files and directories
// point at GitHub. A Japanese page under ja/ mirrors its English source, so its
// links resolve as if from the English source. Links that resolve to nothing
// are left alone for VitePress's dead-link check.
export function resolveLink(from: string, href: string): string {
  if (!href || href.startsWith('#') || /^[a-z][a-z0-9+.-]*:/i.test(href) || href.startsWith('//')) {
    return href
  }
  const hashAt = href.indexOf('#')
  const target = hashAt >= 0 ? href.slice(0, hashAt) : href
  const hash = hashAt >= 0 ? href.slice(hashAt) : ''
  if (!target) return href

  let decoded: string
  try {
    decoded = decodeURI(target)
  } catch {
    return href
  }
  const base = from.startsWith('ja/') ? from.slice(3) : from
  const resolved = decoded.startsWith('/')
    ? path.posix.normalize(decoded.slice(1))
    : path.posix.normalize(path.posix.join(path.posix.dirname(base), decoded))
  if (resolved.startsWith('..')) return href
  const info = stat(resolved)
  if (!info) return href

  if (isPublished(resolved)) {
    if (base !== from && info.isFile() && imageExt.test(resolved)) {
      // ja/ mirrors only documents; images stay at their English path.
      return path.posix.relative(path.posix.dirname(from), resolved) + hash
    }
    if (info.isFile() && (resolved.endsWith('.md') || imageExt.test(resolved))) {
      return target.replace(/(^|\/)README\.md$/, '$1index.md') + hash
    }
    if (info.isDirectory() && hasIndex(resolved)) return href
  }
  const kind = info.isDirectory() ? 'tree' : 'blob'
  const repoPath = resolved === '.' ? '' : `/${kind}/${branch}/${encodeURI(resolved)}`
  return github + repoPath + hash
}

function linkRewriter(md: MarkdownIt) {
  md.core.ruler.after('inline', 'vv-links', (state) => {
    const file: string | undefined = state.env?.path
    if (!file) return
    const from = path.relative(repoRoot, file).split(path.sep).join('/')
    for (const block of state.tokens) {
      for (const token of block.children ?? []) {
        const attr = token.type === 'link_open' ? 'href' : token.type === 'image' ? 'src' : ''
        const value = attr && token.attrGet(attr)
        if (value) token.attrSet(attr, resolveLink(from, value))
      }
    }
  })
}

// 日本語は語を空白で区切らないので、そのままでは全文検索がほとんど当たらない。
// 漢字・かな・カナの連なりは2文字ずつの組に分けて索引にする。連なりの最後の
// 1文字も単独で加え、どの文字も何かの語の先頭になるようにする。前方一致の
// 検索で、語末の1文字（「シーク」の「ク」）だけを探しても当たる。
function tokenize(text: string): string[] {
  const tokens: string[] = []
  for (const part of text.toLowerCase().split(/[\s\p{P}\p{S}]+/u)) {
    if (!part) continue
    for (const run of part.match(/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}ー]+|[^\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}ー]+/gu) ?? []) {
      if (/^[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}ー]+$/u.test(run) && run.length > 1) {
        const chars = [...run]
        for (let i = 0; i < chars.length - 1; i++) tokens.push(chars[i] + chars[i + 1])
        tokens.push(chars[chars.length - 1])
      } else {
        tokens.push(run)
      }
    }
  }
  return tokens
}

// 見出し1を題として読む。サイドバーの表示に使う。
function titleOf(file: string): string {
  const source = fs.readFileSync(path.join(repoRoot, file), 'utf8')
  const m = source.match(/^#[ \t]+(.+?)[ \t#]*$/m)
  return m ? m[1].replace(/[`*]/g, '').trim() : path.posix.basename(file, '.md')
}

function pageLink(file: string): string {
  return '/' + rewrite(file).replace(/(^|\/)index\.md$/, '$1').replace(/\.md$/, '')
}

// ディレクトリの構成どおりのサイドバーを作る。入口（README / index）を先頭に、
// 他の文書を題の順ではなくファイル名の順に並べる（番号付きの specs の順を保つ）。
function sidebarFor(dir: string, collapsed: boolean, overview = 'Overview'): DefaultTheme.SidebarItem[] {
  if (!stat(dir)?.isDirectory()) return []
  const entries = fs.readdirSync(path.join(repoRoot, dir), { withFileTypes: true })
  const index = entries.find((e) => e.isFile() && (e.name === 'README.md' || e.name === 'index.md'))
  const docs = entries
    .filter((e) => e.isFile() && e.name.endsWith('.md') && e !== index)
    .map((e) => e.name)
    .sort()
  const dirs = entries
    .filter((e) => e.isDirectory() && hasMarkdown(path.posix.join(dir, e.name)))
    .map((e) => e.name)
    .sort()
  const items: DefaultTheme.SidebarItem[] = []
  if (index) items.push({ text: overview, link: pageLink(path.posix.join(dir, index.name)) })
  for (const name of docs) {
    const file = path.posix.join(dir, name)
    items.push({ text: titleOf(file), link: pageLink(file) })
  }
  for (const name of dirs) {
    const sub = path.posix.join(dir, name)
    items.push({ text: name, collapsed, items: sidebarFor(sub, true, overview) })
  }
  return items
}

function hasMarkdown(dir: string): boolean {
  return fs
    .readdirSync(path.join(repoRoot, dir), { withFileTypes: true, recursive: true })
    .some((e) => e.isFile() && e.name.endsWith('.md'))
}

// editLink points at the English source, also from a Japanese page: the
// translation is generated and never edited.
function editPattern({ filePath }: { filePath: string }): string {
  return `${github}/edit/${branch}/${filePath.replace(/^ja\//, '')}`
}

const english: DefaultTheme.Config = {
  nav: [
    { text: 'Design', link: '/docs/design-docs/' },
    { text: 'Product specs', link: '/docs/product-specs/' },
    { text: 'How-to', link: '/docs/how-to/' },
    { text: 'Feature plans', link: '/specs/' },
    { text: 'Architecture', link: '/ARCHITECTURE' },
  ],
  sidebar: {
    '/docs/': [
      { text: 'Design', items: sidebarFor('docs/design-docs', true) },
      { text: 'Product specs', items: sidebarFor('docs/product-specs', true) },
      { text: 'How-to', items: sidebarFor('docs/how-to', true) },
    ],
    '/specs/': [{ text: 'Feature plans', items: sidebarFor('specs', true) }],
  },
  editLink: { pattern: editPattern, text: 'Edit on GitHub' },
}

const japanese: DefaultTheme.Config = hasJa
  ? {
      nav: [
        { text: '設計文書', link: '/ja/docs/design-docs/' },
        { text: 'プロダクト仕様', link: '/ja/docs/product-specs/' },
        { text: '手順', link: '/ja/docs/how-to/' },
        { text: '機能ごとの計画', link: '/ja/specs/' },
        { text: 'アーキテクチャ', link: '/ja/ARCHITECTURE' },
      ],
      sidebar: {
        '/ja/docs/': [
          { text: '設計文書', items: sidebarFor('ja/docs/design-docs', true, '概要') },
          { text: 'プロダクト仕様', items: sidebarFor('ja/docs/product-specs', true, '概要') },
          { text: '手順', items: sidebarFor('ja/docs/how-to', true, '概要') },
        ],
        '/ja/specs/': [{ text: '機能ごとの計画', items: sidebarFor('ja/specs', true, '概要') }],
      },
      outline: { level: [2, 3], label: '目次' },
      editLink: { pattern: editPattern, text: '英語の原文を GitHub で編集する' },
      lastUpdated: { text: '最終更新' },
      docFooter: { prev: '前のページ', next: '次のページ' },
      darkModeSwitchLabel: '配色',
      sidebarMenuLabel: 'メニュー',
      returnToTopLabel: '先頭へ戻る',
    }
  : {}

export default defineConfig({
  title: 'vv docs',
  base: '/vv/',
  srcDir: '..',
  srcExclude,
  rewrites: rewrite,
  cleanUrls: true,
  // Examples such as http://localhost:8080 in the guides point at the reader's
  // own machine.
  ignoreDeadLinks: 'localhostLinks',
  lastUpdated: true,
  locales: {
    root: {
      label: 'English',
      lang: 'en',
      description: 'Design documents, specifications and guides for vv',
      themeConfig: english,
    },
    ...(hasJa
      ? {
          ja: {
            label: '日本語',
            lang: 'ja',
            link: '/ja/',
            description: 'vv の設計文書・仕様・手順（英語版からの自動翻訳）',
            themeConfig: japanese,
          },
        }
      : {}),
  },
  vite: {
    // The documents live outside docs-site/, so no node_modules is visible from
    // them. Imports in code generated from documents resolve from docs-site/.
    resolve: {
      alias: [
        {
          find: /^vue(\/.*)?$/,
          replacement: path.join(import.meta.dirname, '../node_modules/vue') + '$1',
        },
      ],
    },
    server: { fs: { allow: [repoRoot] } },
  },
  markdown: {
    anchor: { slugify: slug },
    headers: { slugify: slug },
    config: (md) => md.use(linkRewriter),
  },
  themeConfig: {
    outline: { level: [2, 3] },
    search: {
      provider: 'local',
      options: {
        miniSearch: {
          options: { tokenize },
          searchOptions: { prefix: true, combineWith: 'AND' },
        },
      },
    },
    socialLinks: [{ icon: 'github', link: github }],
  },
})
