//go:build go1.22

// Package extgen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package extgen

import (
	"fmt"
	"net/http"
	"time"
)

// Defines values for ErrorCode.
const (
	ErrorCodeInternal                  ErrorCode = "internal"
	ErrorCodeInvalidRequest            ErrorCode = "invalid_request"
	ErrorCodeMediaFoldersNotConfigured ErrorCode = "media_folders_not_configured"
	ErrorCodeNotFound                  ErrorCode = "not_found"
	ErrorCodeUnauthenticated           ErrorCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeMediaFoldersNotConfigured:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeUnauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for ErrorReason.
const (
	InvalidCursor            ErrorReason = "invalid_cursor"
	NoScan                   ErrorReason = "no_scan"
	TagNameControlCharacters ErrorReason = "tag_name_control_characters"
	TagNameEmpty             ErrorReason = "tag_name_empty"
	TagNameTooLong           ErrorReason = "tag_name_too_long"
	TooManyTags              ErrorReason = "too_many_tags"
	TooManyVideos            ErrorReason = "too_many_videos"
	VideoNotFound            ErrorReason = "video_not_found"
)

// Valid indicates whether the value is a known member of the ErrorReason enum.
func (e ErrorReason) Valid() bool {
	switch e {
	case InvalidCursor:
		return true
	case NoScan:
		return true
	case TagNameControlCharacters:
		return true
	case TagNameEmpty:
		return true
	case TagNameTooLong:
		return true
	case TooManyTags:
		return true
	case TooManyVideos:
		return true
	case VideoNotFound:
		return true
	default:
		return false
	}
}

// Defines values for ExternalScanStatus.
const (
	Done    ExternalScanStatus = "done"
	Failed  ExternalScanStatus = "failed"
	Finding ExternalScanStatus = "finding"
	Partial ExternalScanStatus = "partial"
	Running ExternalScanStatus = "running"
)

// Valid indicates whether the value is a known member of the ExternalScanStatus enum.
func (e ExternalScanStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case Failed:
		return true
	case Finding:
		return true
	case Partial:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Error 誤りの形は画面の API と同じで、index はこの API だけの項目である （contracts/external-api.md §1）。
type Error struct {
	// Code 機械可読なエラー種別。
	Code ErrorCode `json:"code"`

	// Index 原因になった要素の位置（0 から）。タグ名の誤りでは tags の、それ以外では videos の位置を 指す（contracts/external-api.md §4）
	Index *int `json:"index,omitempty"`

	// Limit reason の上限値。上限を持つ reason のときだけ入る
	Limit *int `json:"limit,omitempty"`

	// Message 英語の説明。利用者のプログラムは code と reason で分岐する
	Message string `json:"message"`

	// Reason 同じ code の中で状況を区別する下位の理由。
	Reason *ErrorReason `json:"reason,omitempty"`
}

// ErrorCode 機械可読なエラー種別。
type ErrorCode string

// ErrorReason 同じ code の中で状況を区別する下位の理由。
type ErrorReason string

// ExternalScan defines model for ExternalScan.
type ExternalScan struct {
	// ErrorCode 走査そのものが失敗した理由のコード（status が failed のときだけ入る）
	ErrorCode *string `json:"errorCode"`

	// FinishedAt 走査が終わった時刻。走査中なら null
	FinishedAt *time.Time `json:"finishedAt"`
	Id         int64      `json:"id"`

	// SettledVideos 対象のうち残りの仕事が無い本数。finding のあいだは null。数えたあとは 0 ≤ settledVideos ≤ videos
	SettledVideos *int      `json:"settledVideos"`
	StartedAt     time.Time `json:"startedAt"`

	// Status 取り込みの状態。画面の API の Scan.status と同じ値で、failed は走査そのものの失敗、 finding は対象をまだ数え終えていない、running は走査中か済んでいない対象がある、 partial は失敗の問題がある、done はそれ以外である
	Status ExternalScanStatus `json:"status"`

	// Videos 対象の動画の本数。finding のあいだは null（本数を数え終えていない）
	Videos *int `json:"videos"`
}

// ExternalScanStatus 取り込みの状態。画面の API の Scan.status と同じ値で、failed は走査そのものの失敗、 finding は対象をまだ数え終えていない、running は走査中か済んでいない対象がある、 partial は失敗の問題がある、done はそれ以外である
type ExternalScanStatus string

// Tag defines model for Tag.
type Tag struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`

	// Synonyms 名前の自然順
	Synonyms []string `json:"synonyms"`

	// VideoCount いまライブラリにある動画の本数
	VideoCount int `json:"videoCount"`
}

// TagList defines model for TagList.
type TagList struct {
	Items []Tag `json:"items"`
}

// Internal 誤りの形は画面の API と同じで、index はこの API だけの項目である （contracts/external-api.md §1）。
type Internal = Error

// Unauthenticated 誤りの形は画面の API と同じで、index はこの API だけの項目である （contracts/external-api.md §1）。
type Unauthenticated = Error

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// StartScan スキャンを始める
	// (POST /scans)
	StartScan(w http.ResponseWriter, r *http.Request)
	// GetCurrentScan 直近のスキャンの状態を返す
	// (GET /scans/current)
	GetCurrentScan(w http.ResponseWriter, r *http.Request)
	// ListTags タグの一覧を返す
	// (GET /tags)
	ListTags(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// StartScan operation middleware
func (siw *ServerInterfaceWrapper) StartScan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartScan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentScan operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentScan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentScan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tags", wrapper.ListTags)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/scans", wrapper.StartScan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/scans/current", wrapper.GetCurrentScan)

	return m
}
