//go:build go1.22

// Package extgen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package extgen

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorCode.
const (
	ErrorCodeConflict                  ErrorCode = "conflict"
	ErrorCodeInternal                  ErrorCode = "internal"
	ErrorCodeInvalidRequest            ErrorCode = "invalid_request"
	ErrorCodeMediaFoldersNotConfigured ErrorCode = "media_folders_not_configured"
	ErrorCodeNotFound                  ErrorCode = "not_found"
	ErrorCodeUnauthenticated           ErrorCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeConflict:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeMediaFoldersNotConfigured:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeUnauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for ErrorReason.
const (
	DisplayNameControlCharacters ErrorReason = "display_name_control_characters"
	DisplayNameTooLong           ErrorReason = "display_name_too_long"
	DurationUnknown              ErrorReason = "duration_unknown"
	FileUnavailable              ErrorReason = "file_unavailable"
	InvalidCursor                ErrorReason = "invalid_cursor"
	MergeSameTag                 ErrorReason = "merge_same_tag"
	NoScan                       ErrorReason = "no_scan"
	TagMergeRequired             ErrorReason = "tag_merge_required"
	TagNameControlCharacters     ErrorReason = "tag_name_control_characters"
	TagNameEmpty                 ErrorReason = "tag_name_empty"
	TagNameTaken                 ErrorReason = "tag_name_taken"
	TagNameTooLong               ErrorReason = "tag_name_too_long"
	TagNotFound                  ErrorReason = "tag_not_found"
	ThumbnailFrameUnavailable    ErrorReason = "thumbnail_frame_unavailable"
	ThumbnailPositionOutOfRange  ErrorReason = "thumbnail_position_out_of_range"
	TooManyTags                  ErrorReason = "too_many_tags"
	TooManyVideos                ErrorReason = "too_many_videos"
	VideoNotFound                ErrorReason = "video_not_found"
)

// Valid indicates whether the value is a known member of the ErrorReason enum.
func (e ErrorReason) Valid() bool {
	switch e {
	case DisplayNameControlCharacters:
		return true
	case DisplayNameTooLong:
		return true
	case DurationUnknown:
		return true
	case FileUnavailable:
		return true
	case InvalidCursor:
		return true
	case MergeSameTag:
		return true
	case NoScan:
		return true
	case TagMergeRequired:
		return true
	case TagNameControlCharacters:
		return true
	case TagNameEmpty:
		return true
	case TagNameTaken:
		return true
	case TagNameTooLong:
		return true
	case TagNotFound:
		return true
	case ThumbnailFrameUnavailable:
		return true
	case ThumbnailPositionOutOfRange:
		return true
	case TooManyTags:
		return true
	case TooManyVideos:
		return true
	case VideoNotFound:
		return true
	default:
		return false
	}
}

// Defines values for ExternalScanStatus.
const (
	Done    ExternalScanStatus = "done"
	Failed  ExternalScanStatus = "failed"
	Finding ExternalScanStatus = "finding"
	Partial ExternalScanStatus = "partial"
	Running ExternalScanStatus = "running"
)

// Valid indicates whether the value is a known member of the ExternalScanStatus enum.
func (e ExternalScanStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case Failed:
		return true
	case Finding:
		return true
	case Partial:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for TagSort.
const (
	CountAsc    TagSort = "countAsc"
	CountDesc   TagSort = "countDesc"
	CreatedAsc  TagSort = "createdAsc"
	CreatedDesc TagSort = "createdDesc"
	Name        TagSort = "name"
)

// Valid indicates whether the value is a known member of the TagSort enum.
func (e TagSort) Valid() bool {
	switch e {
	case CountAsc:
		return true
	case CountDesc:
		return true
	case CreatedAsc:
		return true
	case CreatedDesc:
		return true
	case Name:
		return true
	default:
		return false
	}
}

// Defines values for TagSynonymsRequestAction.
const (
	TagSynonymsRequestActionAdd    TagSynonymsRequestAction = "add"
	TagSynonymsRequestActionRemove TagSynonymsRequestAction = "remove"
)

// Valid indicates whether the value is a known member of the TagSynonymsRequestAction enum.
func (e TagSynonymsRequestAction) Valid() bool {
	switch e {
	case TagSynonymsRequestActionAdd:
		return true
	case TagSynonymsRequestActionRemove:
		return true
	default:
		return false
	}
}

// Defines values for VideoTagsRequestAction.
const (
	VideoTagsRequestActionAdd     VideoTagsRequestAction = "add"
	VideoTagsRequestActionRemove  VideoTagsRequestAction = "remove"
	VideoTagsRequestActionReplace VideoTagsRequestAction = "replace"
)

// Valid indicates whether the value is a known member of the VideoTagsRequestAction enum.
func (e VideoTagsRequestAction) Valid() bool {
	switch e {
	case VideoTagsRequestActionAdd:
		return true
	case VideoTagsRequestActionRemove:
		return true
	case VideoTagsRequestActionReplace:
		return true
	default:
		return false
	}
}

// Error 誤りの形は画面の API と同じで、index はこの API だけの項目である （contracts/external-api.md §1）。
type Error struct {
	// Code 機械可読なエラー種別。
	Code ErrorCode `json:"code"`

	// Index 原因になった要素の位置（0 から）。タグ名の誤りでは tags の、表示名・サムネイルの操作では items の、それ以外では videos の位置を指す（contracts/external-api.md §4）
	Index *int `json:"index,omitempty"`

	// Limit reason の上限値。上限を持つ reason のときだけ入る
	Limit *int `json:"limit,omitempty"`

	// Message 英語の説明。利用者のプログラムは code と reason で分岐する
	Message string `json:"message"`

	// Reason 同じ code の中で状況を区別する下位の理由。
	Reason *ErrorReason `json:"reason,omitempty"`

	// TagId 名前がぶつかったタグの id。`tag_name_taken`・`tag_merge_required` のときだけ入る （specs/039-external-tag-admin/contracts/external-api.md §0）
	TagId *int64 `json:"tagId,omitempty"`

	// TagName 名前がぶつかったタグの元の名前（翻訳しない）。`tag_name_taken`・`tag_merge_required` の ときだけ入る
	TagName *string `json:"tagName,omitempty"`
}

// ErrorCode 機械可読なエラー種別。
type ErrorCode string

// ErrorReason 同じ code の中で状況を区別する下位の理由。
type ErrorReason string

// ExternalScan defines model for ExternalScan.
type ExternalScan struct {
	// ErrorCode 走査そのものが失敗した理由のコード（status が failed のときだけ入る）
	ErrorCode *string `json:"errorCode"`

	// FinishedAt 走査が終わった時刻。走査中なら null
	FinishedAt *time.Time `json:"finishedAt"`
	Id         int64      `json:"id"`

	// SettledVideos 対象のうち残りの仕事が無い本数。finding のあいだは null。数えたあとは 0 ≤ settledVideos ≤ videos
	SettledVideos *int      `json:"settledVideos"`
	StartedAt     time.Time `json:"startedAt"`

	// Status 取り込みの状態。画面の API の Scan.status と同じ値で、failed は走査そのものの失敗、 finding は対象をまだ数え終えていない、running は走査中か済んでいない対象がある、 partial は失敗の問題がある、done はそれ以外である
	Status ExternalScanStatus `json:"status"`

	// Videos 対象の動画の本数。finding のあいだは null（本数を数え終えていない）
	Videos *int `json:"videos"`
}

// ExternalScanStatus 取り込みの状態。画面の API の Scan.status と同じ値で、failed は走査そのものの失敗、 finding は対象をまだ数え終えていない、running は走査中か済んでいない対象がある、 partial は失敗の問題がある、done はそれ以外である
type ExternalScanStatus string

// ExternalVideo 動画 1 本。見る人は常に所有者で、非公開の動画も返す
type ExternalVideo struct {
	AddedAt time.Time `json:"addedAt"`

	// ContentKey 内容から決まる識別子。ファイルが移動しても変わらない
	ContentKey string `json:"contentKey"`

	// DisplayName 表示名。未設定は null
	DisplayName *string `json:"displayName"`

	// DurationMs 長さ（ミリ秒）。解析前は null
	DurationMs *int64 `json:"durationMs"`

	// FileCreatedAt 代表の所在（locations の先頭）のファイルの作成日時。ファイルシステムから取れないときは
	// そのファイルの更新日時（mtime）
	FileCreatedAt time.Time `json:"fileCreatedAt"`

	// FileTitle 代表の所在の、拡張子を除いたファイル名
	FileTitle string `json:"fileTitle"`
	Id        int64  `json:"id"`

	// Locations 登録フォルダの下の今の所在。パスの順で、代表が先頭
	Locations []ExternalVideoLocation `json:"locations"`
	Tags      []ExternalVideoTag      `json:"tags"`

	// ThumbnailPositionMs 代表サムネイルの位置（ミリ秒）。未設定は null（自動の位置）
	ThumbnailPositionMs *int64 `json:"thumbnailPositionMs"`

	// Title 有効な題名。表示名があればそれ、無ければ代表の所在（locations の先頭）の題名
	Title string `json:"title"`

	// UpdatedAt vv 上で動画の情報（表示名・タグ・公開設定・代表サムネイル）を最後に編集した日時。
	// 一度も編集していなければ addedAt と同じ。この API の video-tags・display-names も進める
	UpdatedAt time.Time `json:"updatedAt"`
}

// ExternalVideoLocation defines model for ExternalVideoLocation.
type ExternalVideoLocation struct {
	// FileName path の最後の要素
	FileName string `json:"fileName"`

	// Path 絶対パス。ファイルシステムの綴り（NFD を含む）のまま
	Path string `json:"path"`
}

// ExternalVideoPage defines model for ExternalVideoPage.
type ExternalVideoPage struct {
	Items []ExternalVideo `json:"items"`

	// NextCursor 次のページの取得に渡す。続きが無ければ空文字列
	NextCursor string `json:"nextCursor"`
}

// ExternalVideoTag defines model for ExternalVideoTag.
type ExternalVideoTag struct {
	// FromFolder 祖先のフォルダ名から付く（この API では外れない）
	FromFolder bool  `json:"fromFolder"`
	Id         int64 `json:"id"`

	// Manual 手で付けた（この API の付け外しの対象）
	Manual bool   `json:"manual"`
	Name   string `json:"name"`

	// Tentative 仮のタグ（自動の付与で新しく作られ、まだ確定していないタグ）
	Tentative bool `json:"tentative"`
}

// Tag defines model for Tag.
type Tag struct {
	// CreatedAt タグを作った時刻。`sort` の `createdDesc`・`createdAsc` はこの値で並べる
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`

	// Synonyms 名前の自然順
	Synonyms []string `json:"synonyms"`

	// Tentative 仮のタグ（自動の付与で新しく作られ、まだ確定していないタグ）
	Tentative bool `json:"tentative"`

	// VideoCount いまライブラリにある動画の本数
	VideoCount int `json:"videoCount"`
}

// TagList defines model for TagList.
type TagList struct {
	Items []Tag `json:"items"`

	// NextCursor 次のページの取得に渡す。`limit` を付けた要求で続きがあるときだけ入る
	NextCursor *string `json:"nextCursor,omitempty"`

	// Total 条件（`q`・`tentative`・`unused`）に合うタグの数。ページングとは独立に返る
	Total int `json:"total"`

	// TotalAll 全部のタグの数。ページングとは独立に返る
	TotalAll int `json:"totalAll"`
}

// TagMergeRequest defines model for TagMergeRequest.
type TagMergeRequest struct {
	// SourceIds 統合するタグ。送った数で 1〜20,000 件（重複も数に入り、統合は 1 回）。範囲外は `too_many_tags`
	SourceIds []int64 `json:"sourceIds"`

	// TargetId 付与・名前・シノニムを受け取るタグ。確定したタグになる
	TargetId int64 `json:"targetId"`
}

// TagMergeResponse defines model for TagMergeResponse.
type TagMergeResponse struct {
	// NotFoundIds 無かったので飛ばした統合元。無ければ空
	NotFoundIds []int64 `json:"notFoundIds"`
	Tag         Tag     `json:"tag"`
}

// TagRenameRequest defines model for TagRenameRequest.
type TagRenameRequest struct {
	Id int64 `json:"id"`

	// Name 新しい元の名前。タグ名と同じ規則で整える
	Name string `json:"name"`
}

// TagSort タグの一覧の並び順。name は名前の自然順（向きは無い）、countDesc・countAsc は本数、
// createdDesc・createdAsc は作った日。値が同じタグは名前の自然順、それも同じなら id
// （specs/036-tag-admin-scale/data-model.md §0・§2）
type TagSort string

// TagSynonymsRequest defines model for TagSynonymsRequest.
type TagSynonymsRequest struct {
	// Action add は足す、remove は外す
	Action TagSynonymsRequestAction `json:"action"`

	// Id シノニムを変えるタグ
	Id int64 `json:"id"`

	// MergeTagId `add` だけ: 統合を受け入れるタグの id。`tag_merge_required` の `tagId` を渡す。名前が別のタグの 元の名前でなければ無視する
	MergeTagId *int64 `json:"mergeTagId,omitempty"`

	// Name シノニム。タグ名と同じ規則で整える
	Name string `json:"name"`
}

// TagSynonymsRequestAction add は足す、remove は外す
type TagSynonymsRequestAction string

// VideoDisplayNameChange defines model for VideoDisplayNameChange.
type VideoDisplayNameChange struct {
	// DisplayName 表示名。null、または前後の空白を除いて空なら解除する。制御文字を含めず、整えた後で 200 符号位置まで
	DisplayName *string `json:"displayName"`

	// Video 動画の指定。id・contentKey・path のちょうど 1 つを持つ。path は正規化せず、登録フォルダの下の 今の所在の path とバイト列で比べる
	Video VideoRef `json:"video"`
}

// VideoDisplayNamesItem defines model for VideoDisplayNamesItem.
type VideoDisplayNamesItem struct {
	// DisplayName 反映後の表示名。解除したら null
	DisplayName *string `json:"displayName"`

	// FileTitle 代表の所在の、拡張子を除いたファイル名
	FileTitle string `json:"fileTitle"`

	// Title 反映後の有効な題名
	Title string         `json:"title"`
	Video VideoTagsVideo `json:"video"`
}

// VideoDisplayNamesRequest defines model for VideoDisplayNamesRequest.
type VideoDisplayNamesRequest struct {
	// Items 1〜20000 件。範囲外は `too_many_videos`
	Items []VideoDisplayNameChange `json:"items"`
}

// VideoDisplayNamesResponse defines model for VideoDisplayNamesResponse.
type VideoDisplayNamesResponse struct {
	// Items items の順
	Items []VideoDisplayNamesItem `json:"items"`
}

// VideoRef 動画の指定。id・contentKey・path のちょうど 1 つを持つ。path は正規化せず、登録フォルダの下の 今の所在の path とバイト列で比べる
type VideoRef struct {
	ContentKey *string `json:"contentKey,omitempty"`
	Id         *int64  `json:"id,omitempty"`
	Path       *string `json:"path,omitempty"`
}

// VideoTagsItem defines model for VideoTagsItem.
type VideoTagsItem struct {
	// Tags 操作後のタグ（手で付けた分とフォルダ名から付く分、出所つき）
	Tags  []ExternalVideoTag `json:"tags"`
	Video VideoTagsVideo     `json:"video"`
}

// VideoTagsRequest defines model for VideoTagsRequest.
type VideoTagsRequest struct {
	// Action add は付ける、remove は外す、replace は手で付けたタグをちょうど tags の集合にする （空なら手で付けたタグをすべて外す）
	Action VideoTagsRequestAction `json:"action"`

	// Tags タグの名前（シノニムも可）。100 件まで。add・remove では 1 件以上。範囲外は `too_many_tags`
	Tags []string `json:"tags"`

	// Tentative 真なら add・replace で、どのタグの名前にもシノニムにも当たらない名前を仮のタグとして作る。 却下した名前（綴りの完全一致）は作らず付けずに飛ばし、skippedTags に返す。既存のタグに 当たる名前はそのタグを付け、その状態を変えない。remove では何も変えない
	Tentative *bool `json:"tentative,omitempty"`

	// Videos 1〜20000 件。範囲外は `too_many_videos`
	Videos []VideoRef `json:"videos"`
}

// VideoTagsRequestAction add は付ける、remove は外す、replace は手で付けたタグをちょうど tags の集合にする （空なら手で付けたタグをすべて外す）
type VideoTagsRequestAction string

// VideoTagsResponse defines model for VideoTagsResponse.
type VideoTagsResponse struct {
	// Items videos の順
	Items []VideoTagsItem `json:"items"`

	// SkippedTags tentative が真の add・replace で、却下した名前に当たって飛ばした名前。整えた形で tags の順に 1 回ずつ。無ければ空の配列
	SkippedTags []string `json:"skippedTags"`
}

// VideoTagsVideo defines model for VideoTagsVideo.
type VideoTagsVideo struct {
	ContentKey string `json:"contentKey"`
	Id         int64  `json:"id"`
}

// VideoThumbnailChange defines model for VideoThumbnailChange.
type VideoThumbnailChange struct {
	// PositionMs 代表サムネイルにする場面の位置（ミリ秒、0 以上で尺未満）。null なら解除し、自動の位置に戻す
	PositionMs *int64 `json:"positionMs"`

	// Video 動画の指定。id・contentKey・path のちょうど 1 つを持つ。path は正規化せず、登録フォルダの下の 今の所在の path とバイト列で比べる
	Video VideoRef `json:"video"`
}

// VideoThumbnailsItem defines model for VideoThumbnailsItem.
type VideoThumbnailsItem struct {
	// ThumbnailPositionMs 反映後の位置。解除したら null
	ThumbnailPositionMs *int64         `json:"thumbnailPositionMs"`
	Video               VideoTagsVideo `json:"video"`
}

// VideoThumbnailsRequest defines model for VideoThumbnailsRequest.
type VideoThumbnailsRequest struct {
	// Items 1〜20 件。範囲外は `too_many_videos`
	Items []VideoThumbnailChange `json:"items"`
}

// VideoThumbnailsResponse defines model for VideoThumbnailsResponse.
type VideoThumbnailsResponse struct {
	// Items items の順
	Items []VideoThumbnailsItem `json:"items"`
}

// Internal 誤りの形は画面の API と同じで、index はこの API だけの項目である （contracts/external-api.md §1）。
type Internal = Error

// Unauthenticated 誤りの形は画面の API と同じで、index はこの API だけの項目である （contracts/external-api.md §1）。
type Unauthenticated = Error

// ListTagsParams defines parameters for ListTags.
type ListTagsParams struct {
	// Q 検索語。全角・半角、大文字・小文字、ひらがな・カタカナなどの表記の揺れを吸収した形
	// （照合形）にして前後の空白を落とし、空でなければ元の名前かシノニムに部分一致する
	// タグだけにする。語の分解はしない
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Tentative true なら仮のタグだけにする
	Tentative *bool `form:"tentative,omitempty" json:"tentative,omitempty"`

	// Unused true なら本数 0 のタグだけにする
	Unused *bool `form:"unused,omitempty" json:"unused,omitempty"`

	// Sort 並び順
	Sort *TagSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Cursor 前回の応答が返した `nextCursor`。中身は不透明で、解釈しない。同じ `q`・`tentative`・
	// `unused`・`sort` で続けて使う。`limit` を省いたときは無視する
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit 1 ページの件数。省くと全件を返し、`nextCursor` は入らない
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListVideosParams defines parameters for ListVideos.
type ListVideosParams struct {
	// Cursor 前回の応答が返した `nextCursor`。中身は不透明で、解釈しない。省略すると先頭から
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit 1 ページの件数。範囲外は `400` `invalid_request`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// LookupVideoParams defines parameters for LookupVideo.
type LookupVideoParams struct {
	Id         *int64  `form:"id,omitempty" json:"id,omitempty"`
	ContentKey *string `form:"contentKey,omitempty" json:"contentKey,omitempty"`

	// Path 所在の絶対パス
	Path *string `form:"path,omitempty" json:"path,omitempty"`
}

// MergeTagsJSONRequestBody defines body for MergeTags for application/json ContentType.
type MergeTagsJSONRequestBody = TagMergeRequest

// RenameTagJSONRequestBody defines body for RenameTag for application/json ContentType.
type RenameTagJSONRequestBody = TagRenameRequest

// UpdateTagSynonymsJSONRequestBody defines body for UpdateTagSynonyms for application/json ContentType.
type UpdateTagSynonymsJSONRequestBody = TagSynonymsRequest

// UpdateVideoDisplayNamesJSONRequestBody defines body for UpdateVideoDisplayNames for application/json ContentType.
type UpdateVideoDisplayNamesJSONRequestBody = VideoDisplayNamesRequest

// UpdateVideoTagsJSONRequestBody defines body for UpdateVideoTags for application/json ContentType.
type UpdateVideoTagsJSONRequestBody = VideoTagsRequest

// UpdateVideoThumbnailsJSONRequestBody defines body for UpdateVideoThumbnails for application/json ContentType.
type UpdateVideoThumbnailsJSONRequestBody = VideoThumbnailsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// StartScan スキャンを始める
	// (POST /scans)
	StartScan(w http.ResponseWriter, r *http.Request)
	// GetCurrentScan 直近のスキャンの状態を返す
	// (GET /scans/current)
	GetCurrentScan(w http.ResponseWriter, r *http.Request)
	// ListTags タグの一覧を返す
	// (GET /tags)
	ListTags(w http.ResponseWriter, r *http.Request, params ListTagsParams)
	// MergeTags 複数のタグを 1 つのタグへ統合する
	// (POST /tags/merge)
	MergeTags(w http.ResponseWriter, r *http.Request)
	// RenameTag タグの元の名前を変える
	// (POST /tags/rename)
	RenameTag(w http.ResponseWriter, r *http.Request)
	// UpdateTagSynonyms タグのシノニムを足す・外す
	// (POST /tags/synonyms)
	UpdateTagSynonyms(w http.ResponseWriter, r *http.Request)
	// UpdateVideoDisplayNames 複数の動画の表示名を設定・解除する
	// (POST /video-display-names)
	UpdateVideoDisplayNames(w http.ResponseWriter, r *http.Request)
	// UpdateVideoTags 複数の動画に名前で指定したタグを付ける・外す・置き換える
	// (POST /video-tags)
	UpdateVideoTags(w http.ResponseWriter, r *http.Request)
	// UpdateVideoThumbnails 複数の動画の代表サムネイルの位置を設定・解除する
	// (POST /video-thumbnails)
	UpdateVideoThumbnails(w http.ResponseWriter, r *http.Request)
	// ListVideos 動画の一覧をページを分けて返す
	// (GET /videos)
	ListVideos(w http.ResponseWriter, r *http.Request, params ListVideosParams)
	// LookupVideo 動画を 1 本、id・内容キー・パスのどれかで引く
	// (GET /videos/lookup)
	LookupVideo(w http.ResponseWriter, r *http.Request, params LookupVideoParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// StartScan operation middleware
func (siw *ServerInterfaceWrapper) StartScan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartScan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentScan operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentScan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentScan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTagsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tentative" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tentative", r.URL.Query(), &params.Tentative, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tentative"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tentative", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "unused" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "unused", r.URL.Query(), &params.Unused, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "unused"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "unused", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTags(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MergeTags operation middleware
func (siw *ServerInterfaceWrapper) MergeTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MergeTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameTag operation middleware
func (siw *ServerInterfaceWrapper) RenameTag(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameTag(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTagSynonyms operation middleware
func (siw *ServerInterfaceWrapper) UpdateTagSynonyms(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTagSynonyms(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateVideoDisplayNames operation middleware
func (siw *ServerInterfaceWrapper) UpdateVideoDisplayNames(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateVideoDisplayNames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateVideoTags operation middleware
func (siw *ServerInterfaceWrapper) UpdateVideoTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateVideoTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateVideoThumbnails operation middleware
func (siw *ServerInterfaceWrapper) UpdateVideoThumbnails(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateVideoThumbnails(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVideos operation middleware
func (siw *ServerInterfaceWrapper) ListVideos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVideosParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVideos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupVideo operation middleware
func (siw *ServerInterfaceWrapper) LookupVideo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LookupVideoParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "contentKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "contentKey", r.URL.Query(), &params.ContentKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "contentKey"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contentKey", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupVideo(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/videos", wrapper.ListVideos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/videos/lookup", wrapper.LookupVideo)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/video-tags", wrapper.UpdateVideoTags)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/video-display-names", wrapper.UpdateVideoDisplayNames)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/video-thumbnails", wrapper.UpdateVideoThumbnails)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tags", wrapper.ListTags)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tags/merge", wrapper.MergeTags)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tags/rename", wrapper.RenameTag)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tags/synonyms", wrapper.UpdateTagSynonyms)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/scans", wrapper.StartScan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/scans/current", wrapper.GetCurrentScan)

	return m
}
